### ISSUE TITLE
[Reopened] Friedman Gold-72 No More Tears Wah Pedal

### ISSUE THREAD

**Issue by raulfragoso** [PedalPlayground/PedalPlayground.github.io#740]
Note: this pedal has been already added via issue #702 and closed via issue #691 but the image currently used on pedalplayground.com is incorrect, so I'm reopening it with the correct image again to it can be fixed.

![143909260-aedc5117-7412-4a82-a3d8-548aebd45735](https://user-images.githubusercontent.com/1527775/147881082-1e277a46-8712-4825-96fa-c0aa155d4527.png)

Brand: Friedman
Name: Friedman Gold-72 No More Tears Wah Pedal
Height: 9.95 inches
Width: 3.97 inches

**Comment by XlosVSM** [comment]
Yeah, sorry I put in the wrong file name. It is being fixed in my latest pr.

**Comment by raulfragoso** [comment]
The image on pedalplayground.com is still wrong:

<img width="540" alt="2022-09-27_16-36-30" src="https://user-images.githubusercontent.com/1527775/192619610-1e99048f-3d32-4d77-8bc3-c1bb00e4ff50.png">
